# Generated by Django 2.1.4 on 2019-01-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('biaya', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Ada'), ('K', 'Kosong')], max_length=1)),
            ],
        ),
    ]
