# Generated by Django 2.1.4 on 2019-01-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='satuan',
            field=models.CharField(choices=[('Pcs', 'Potong'), ('Kg', 'Kilo')], default='Kg', max_length=3),
        ),
    ]
