# Generated by Django 2.1.4 on 2019-01-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_layanan_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='status',
            field=models.CharField(choices=[('A', 'Ada'), ('K', 'Kosong')], default='A', max_length=1),
        ),
    ]
