# Generated by Django 2.1.4 on 2019-01-04 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_auto_20190104_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='biaya',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
