# Generated by Django 2.1.4 on 2019-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0005_auto_20190104_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='nama',
            field=models.CharField(max_length=30),
        ),
    ]
