# Generated by Django 2.1.4 on 2019-01-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_auto_20190104_1545'),
        ('layanan', '0005_auto_20190104_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, max_length=240)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layanan.Layanan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
