# Generated by Django 2.1.4 on 2019-01-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='hrg_satuan',
            field=models.FloatField(default=0),
        ),
    ]
