# Generated by Django 2.1.4 on 2019-01-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detailorder', '0002_detailorder_hrg_satuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='layanan',
            field=models.CharField(default='Cuci dan Setrika', max_length=30),
        ),
    ]
