# Generated by Django 2.1.4 on 2019-01-04 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parfum', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jenis',
            field=models.CharField(choices=[('R', 'Reguler'), ('E', 'Express')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='parfum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parfum.Parfum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='posisi',
            field=models.CharField(choices=[('T', 'Tagging'), ('C', 'Cuci'), ('S', 'Setrika'), ('R', 'Rak')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='tanggalAmbil',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalBiaya',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
