# Generated by Django 2.1.4 on 2019-01-04 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_auto_20190104_1216'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20190104_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nomor',
            field=models.CharField(default='000001', max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pelanggan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pelanggan.Pelanggan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
