# Generated by Django 2.1.4 on 2019-01-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190104_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='catatan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='posisi',
            field=models.CharField(choices=[('T', 'Tagging'), ('C', 'Cuci'), ('S', 'Setrika'), ('R', 'Rak'), ('A', 'Ambil')], default='T', max_length=1),
        ),
    ]
