# Generated by Django 2.1.4 on 2019-01-04 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190104_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='catatan',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tanggalAmbil',
            field=models.DateField(default=datetime.date(2019, 1, 7), null=True),
        ),
    ]
