# Generated by Django 2.1.4 on 2019-01-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190104_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='catatan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
